/*****************************************************************************
 * Author: Mhd Moukaddam  contact address: moukaddam@triumf.ca      		 *
 *---------------------------------------------------------------------------*
 * Decription: This class stores the convered data from a root file 
               generated by the dcptoroot.cxx macro. 
               It is intended a an intermediate analysis class to arrange 
               the data in an optimized/condensed (zeros free) root tree 
               structure
 *---------------------------------------------------------------------------*
 * Comment:                                                                  *
 *                                                                           *
 *                                                                           *
 *****************************************************************************/

//c++
#include <iostream>
using namespace std;

// User classes
#include "TMielData.h"

//Root 
ClassImp(TMielData)

// -------------------------

TMielData::TMielData() {
   Clear();
}

TMielData::~TMielData() {
}


void TMielData::Clear() {

	fMielSegment.clear();
	fMielCharge.clear();
	fMielEnergy.clear();
	fMielTime.clear(); 

  fMielChopper=-1;
	fMielAptherix=-1; 
	fMielHallProbe=-1; 
	fMielVcontE=-1; 
	fMielVcontG=-1; 

}



void TMielData::Print() {

	cout << " P R I N T  -- E V E N T  \n" ;
	cout << "==========================\n" ; 

	cout << "Miel Segment : " << fMielSegment.size() <<"\n" ;
	for (unsigned i = 0 ; i < fMielSegment.size() ; i++ ) {
	cout << " "<< fMielSegment.at(i)<<"\t";
	}
	cout << "\n-------------------------\n" ; 
	
	cout << "Miel Charge : " << fMielCharge.size() <<"\n" ;
	for (unsigned i = 0 ; i < fMielCharge.size() ; i++ ) {
	cout << " "<< fMielCharge.at(i)<<"\t";
	}
	cout << "\n-------------------------\n" ; 

	cout << "Miel Energy : " << fMielEnergy.size() <<"\n" ;
	for (unsigned i = 0 ; i < fMielEnergy.size() ; i++ ) {
	cout << " "<< fMielEnergy.at(i)<<"\t";
	}
	cout << "\n-------------------------\n" ; 

	cout << "Miel Time : " << fMielTime.size() <<"\n" ;
	for (unsigned i = 0 ; i < fMielTime.size() ; i++ ) {
	cout << " "<< fMielTime.at(i)<<"\t";
	}
	cout << "\n-------------------------\n" ; 

	cout << "Miel Aptherix : " << fMielAptherix <<"\n" ;
	cout << "Miel HallProbe : " << fMielHallProbe <<"\n" ;
	cout << "Miel VcontE : " << fMielVcontE <<"\n" ;
	cout << "Miel VcontG : " << fMielVcontG <<"\t" ;
	cout << "\n-------------------------\n" ; 

}
